[tool.ruff]
# Enable all rules
select = ["ALL"]

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Same as Black.
line-length = 80

# Assume Python 3.10
target-version = "py310"

# cache directory 
cache-dir = "~/.cache/ruff"
